name: SSH Server Deploy
on:
  push:
    branches: [ main ]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing abhinav vm server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.29.251
          username: abhinav
          key: ${{ PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/html-project
            git pull origin master
            git status
