name: SSH Server Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.SERVER_HOST }}
      - name: Pull
        run: ssh git-user@14.97.156.238 "cd /var/www/html/ && /usr/bin/git pull origin main"
